# output
Output command.gif

# Set
Set Shell "zsh"
Set FontSize 12
Set Width 1800
Set Height 1200
Set Theme "Catppuccin Frappe"
Set Padding 20
Set Margin 20
Set MarginFill "#11111b"
Set WindowBar Colorful
Set BorderRadius 12
Set Framerate 60
Set PlaybackSpeed 0.9
Set CursorBlink false
Set TypingSpeed 140ms

Type "lsmux htop"
Enter
Sleep 1000ms
Type "vm-"
Sleep 1000ms
Ctrl+A
Sleep 500ms
Enter
Sleep 20s
