# Enviroment
# ====================
# [env]
# mise.file = "env"

# Tasks(binary)
# ====================
[tasks.binaly_install]
description = "Install binary files lssh, lscp and lsftp"
depends = ["binary_build"]
run = """
    cp lssh /usr/local/bin/lssh
    cp lscp /usr/local/bin/lscp
    cp lsftp /usr/local/bin/lsftp
"""

[tasks.binary_build]
description = "Build binary files lssh, lscp and lsftp"
depends = ["binary_clean"]
run = """
    go mod tidy
    go mod vendor

    go build -o lssh ./cmd/lssh
    go build -o lscp ./cmd/lscp
    go build -o lsftp ./cmd/lsftp
"""

[tasks.binary_clean]
description = "Clean binary files lssh, lscp and lsftp"
depends = []
run = """
    rm -f lssh lscp lsftp
"""
