[log]
enable = true
timestamp = true
dirpath = "~/.lssh/logs"

[includes]
path = [
    "~/.lssh.d/servers_proxy.toml",
    "~/.lssh.d/servers_direct.toml",
    "~/.lssh.d/servers_match.toml"
]

[common]
user = "demo"
port = "22"
pass = "demo-password"
local_rc = "no"
# Sourcing from bashrc is not supported, so specify the files that contain the actual code.
local_rc_file = [
    "~/.demo_localrc/bash_prompt",
    "~/.demo_localrc/sh_alias",
    "~/.demo_localrc/sh_export",
    "~/.demo_localrc/sh_function",
    "~/.demo_localrc/generated/lvim.sh",
    "~/.demo_localrc/generated/ltmux.sh",
]
ssh_agent_key = ["~/.ssh/demo_lssh_ed25519"]
ssh_agent = true

[proxy.http_proxy]
addr = "172.31.0.32"
port = "8888"
note = "http connect proxy"

[proxy.socks_proxy]
addr = "172.31.0.33"
port = "1080"
note = "socks5 proxy"

[proxy.deep_http_proxy]
addr = "172.31.2.61"
port = "8888"
proxy = "OverSshProxy"
note = "http proxy behind OverSshProxy"

[proxy.deep_socks_proxy]
addr = "172.31.2.62"
port = "1080"
proxy = "OverSshProxy"
note = "socks5 proxy behind OverSshProxy"
