[log]
enable = true
timestamp = true
dirpath = "~/.lssh/logs"

[includes]
path = [
    "~/.lssh.d/servers_proxy.toml",
    "~/.lssh.d/servers_direct.toml"
]

[common]
user = "demo"
port = "22"
local_rc = "no"
# Sourcing from bashrc is not supported, so specify the files that contain the actual code.
local_rc_file = [
    "~/.demo_localrc/bash_prompt",
    "~/.demo_localrc/sh_alias",
    "~/.demo_localrc/sh_export",
    "~/.demo_localrc/sh_function",
]
ssh_agent_key = ["~/.ssh/demo_lssh_ed25519"]
ssh_agent = true

[proxy.http_proxy]
addr = "172.31.0.32"
port = "8888"
note = "http connect proxy"

[proxy.socks_proxy]
addr = "172.31.0.33"
port = "1080"
note = "socks5 proxy"
