logoutput: stderr
internal: 172.31.0.33 port = 1080
external: 172.31.1.33
socksmethod: none
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 172.31.0.0/24 to: 0.0.0.0/0
    log: connect disconnect error
}

socks pass {
    from: 172.31.0.0/24 to: 0.0.0.0/0
    command: bind connect udpassociate
    log: connect disconnect error
    socksmethod: none
}
