logoutput: stderr
internal: 0.0.0.0 port = 1080
external: __SOCKS_EXTERNAL_ADDR__
socksmethod: none
user.privileged: root
user.unprivileged: nobody

client pass {
    from: __SOCKS_ALLOW_FROM__ to: 0.0.0.0/0
    log: connect disconnect error
}

socks pass {
    from: __SOCKS_ALLOW_FROM__ to: 0.0.0.0/0
    command: bind connect udpassociate
    log: connect disconnect error
    socksmethod: none
}
