// Copyright (c) 2026 Blacknon. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.

package conf

import (
	"bytes"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// GenerateLSSHConfigFromOpenSSH renders OpenSSH host entries as a minimal
// lssh config file that can be written to stdout or saved by the caller.
func GenerateLSSHConfigFromOpenSSH(path, command string) ([]byte, error) {
	entries, err := loadOpenSSHConfigEntries(path, command)
	if err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("no concrete hosts found in OpenSSH config")
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Host < entries[j].Host
	})

	buf := &bytes.Buffer{}
	buf.WriteString("# Generated by lssh --generate-lssh-conf\n")
	buf.WriteString("# Review and adjust values before long-term use.\n\n")

	for i, entry := range entries {
		if i > 0 {
			buf.WriteByte('\n')
		}

		fmt.Fprintf(buf, "[server.%s]\n", entry.Host)
		writeServerConfigTOML(buf, entry.Config)
	}

	return buf.Bytes(), nil
}

func writeServerConfigTOML(buf *bytes.Buffer, cfg ServerConfig) {
	values := serverConfigToTOMLMap(cfg)
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		fmt.Fprintf(buf, "%s = %s\n", key, tomlValueString(values[key]))
	}
}

func serverConfigToTOMLMap(cfg ServerConfig) map[string]interface{} {
	result := map[string]interface{}{}

	value := reflect.ValueOf(cfg)
	typ := reflect.TypeOf(cfg)
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		tag := field.Tag.Get("toml")
		if tag == "" || tag == "-" {
			continue
		}

		switch field.Name {
		case "Forwards", "Match":
			continue
		}

		fieldValue := value.Field(i)
		if fieldValue.IsZero() {
			continue
		}

		result[tag] = fieldValue.Interface()
	}

	for key, value := range cfg.ProviderConfig {
		if _, ok := result[key]; ok {
			continue
		}
		result[key] = value
	}

	return result
}

func serverConfigTOMLKeys() []string {
	typ := reflect.TypeOf(ServerConfig{})
	keys := make([]string, 0, typ.NumField())
	for i := 0; i < typ.NumField(); i++ {
		tag := typ.Field(i).Tag.Get("toml")
		if tag == "" || tag == "-" {
			continue
		}
		keys = append(keys, tag)
	}
	sort.Strings(keys)
	return keys
}

func tomlValueString(v interface{}) string {
	switch value := v.(type) {
	case string:
		return fmt.Sprintf("%q", value)
	case []string:
		if len(value) == 0 {
			return "[]"
		}

		quoted := make([]string, 0, len(value))
		for _, item := range value {
			quoted = append(quoted, fmt.Sprintf("%q", item))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	case bool:
		if value {
			return "true"
		}
		return "false"
	case int:
		return fmt.Sprintf("%d", value)
	case int64:
		return fmt.Sprintf("%d", value)
	case ControlPersistDuration:
		return fmt.Sprintf("%d", int64(value))
	default:
		return fmt.Sprintf("%q", fmt.Sprint(v))
	}
}
