http_port 8888

acl localnet src 172.31.0.0/24
acl localnet src 172.31.1.0/24
acl localnet src 172.31.2.0/24
acl ssl_ports port 22
acl connect method CONNECT

http_access allow localnet connect ssl_ports
http_access deny all

pid_filename /tmp/squid.pid
coredump_dir /var/spool/squid
